services:
  smtp:
    container_name: smtp
    hostname: smtp
    image: arsartori/postfix:latest
    ports:
      - 25:25
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /opt/docker/smtp/queue:/var/log/queue.new
    environment:
      RELAYHOST: smtp.server
      MYNETWORKS: 0.0.0.0/0
      MYHOSTNAME: smtp.localhost
