services:
  smtp:
    container_name: smtp
    hostname: smtp
    image: arsartori/postfix
    ports:
      - 25:25
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /opt/docker/smtp/queue:/var/log/queue.new
    environment:
      RELAYHOST: smtp.localhost
      MYNETWORKS: 0.0.0.0/0
      MYHOSTNAME: smtp.lab.corp
    networks:
      - net-app

networks:
  net-app:
    name: net-app
    external: true
